/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg_calculadora_de_vigas;

import javax.swing.JOptionPane;

/**
 *
 * @author BOTAR O NOME DO USUARIO DO WINDOWS QUE TTEORICAMENTE FARIA
 */
public class InterfaceCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceCalculadora
     * aqui estão iniciando as variaveis também
     */
    double altura = 0;
    double base = 0;
    double comprimento = 0;
    double carga = 0;
    int    tipo =0;
    
    public InterfaceCalculadora() {
        initComponents();
        setSize(300,500); //largura e altura do form
       setLocationRelativeTo(null); //Centraliza o form
         
 
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbl_titulo = new javax.swing.JLabel();
        rbt_engastado = new javax.swing.JRadioButton();
        rbt_biapoiado = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txt_altura = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_base = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_comprimento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_carga = new javax.swing.JTextField();
        cbb_material = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_momento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_tnormal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_tlinha = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_deformacao = new javax.swing.JTextField();
        btn_limpardados = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_calcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 200, 300));
        setSize(new java.awt.Dimension(300, 400));
        getContentPane().setLayout(null);

        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText("Calculadora de Vigas");
        lbl_titulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbl_titulo);
        lbl_titulo.setBounds(20, 10, 250, 18);

        buttonGroup1.add(rbt_engastado);
        rbt_engastado.setText("Engastado");
        rbt_engastado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_engastadoActionPerformed(evt);
            }
        });
        getContentPane().add(rbt_engastado);
        rbt_engastado.setBounds(30, 30, 110, 21);

        buttonGroup1.add(rbt_biapoiado);
        rbt_biapoiado.setText("Biapoiado");
        getContentPane().add(rbt_biapoiado);
        rbt_biapoiado.setBounds(160, 30, 110, 21);

        jLabel2.setText("Altura (m):");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 60, 57, 16);

        txt_altura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alturaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_altura);
        txt_altura.setBounds(150, 60, 110, 22);

        jLabel3.setText("Base    (m):");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 90, 80, 16);
        getContentPane().add(txt_base);
        txt_base.setBounds(150, 90, 110, 22);

        jLabel4.setText("Comprimento (m):");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 120, 110, 16);
        getContentPane().add(txt_comprimento);
        txt_comprimento.setBounds(190, 120, 71, 22);

        jLabel5.setText("Carga  (n)");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 150, 60, 16);
        getContentPane().add(txt_carga);
        txt_carga.setBounds(150, 150, 110, 22);

        cbb_material.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Madeira", "Aço", "Alumínio" }));
        cbb_material.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_materialActionPerformed(evt);
            }
        });
        getContentPane().add(cbb_material);
        cbb_material.setBounds(150, 180, 110, 22);

        jLabel6.setText("Material:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 180, 50, 16);

        jLabel7.setText("Momento de I (m4)");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 220, 110, 16);

        txt_momento.setEditable(false);
        getContentPane().add(txt_momento);
        txt_momento.setBounds(190, 220, 71, 22);

        jLabel8.setText("Tensão Normal (Pa)");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 250, 120, 16);

        txt_tnormal.setEditable(false);
        getContentPane().add(txt_tnormal);
        txt_tnormal.setBounds(190, 250, 70, 22);

        jLabel9.setText("Tensão de Linhamento (pa)");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 280, 190, 16);

        txt_tlinha.setEditable(false);
        getContentPane().add(txt_tlinha);
        txt_tlinha.setBounds(190, 280, 71, 22);

        jLabel10.setText("Deformação");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 310, 70, 16);

        txt_deformacao.setEditable(false);
        getContentPane().add(txt_deformacao);
        txt_deformacao.setBounds(190, 310, 70, 22);

        btn_limpardados.setText("Limpar Dados");
        btn_limpardados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpardadosActionPerformed(evt);
            }
        });
        getContentPane().add(btn_limpardados);
        btn_limpardados.setBounds(20, 350, 120, 40);

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancelar);
        btn_cancelar.setBounds(160, 350, 100, 40);

        btn_calcular.setText("Calcular");
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });
        getContentPane().add(btn_calcular);
        btn_calcular.setBounds(100, 410, 100, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbt_engastadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_engastadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_engastadoActionPerformed

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed

 
        altura = Double.parseDouble(txt_altura.getText()); //cria a variavel altura e ja le o texto
        base = Double.parseDouble(txt_base.getText()); //cria a variavel base e ja le o texto
        comprimento = Double.parseDouble(txt_comprimento.getText()); //cria a variavel base e ja le o texto
        carga = Double.parseDouble(txt_carga.getText()); //cria a variavel carga e ja le o texto
 
if(rbt_engastado.isSelected()){
            tipo = 1; // 1 para engastado
            
        }
        else if(rbt_biapoiado.isSelected()){
            tipo = 2; // 2 para biapoiado
        }//fim do if para o radio button
     
  System.out.println(tipo);
 
 
  if( cbb_material.getSelectedItem() == "Aço"){  
      
      double ModulodeElasticidade = 200*(Math.pow(10, 9));   
 	double MI;
        
        //Calculo do momento de inercia
        
        MI = (((Math.pow(altura,3))*base)/12); // MOMENTO DE INERCIA
 		txt_momento.setText(""+MI);
                
       //Calculo da tensão normal;
       double TNM = (carga/(base*altura)); //TENSÃO NORMAL
 		 txt_tnormal.setText(""+TNM);
                
       //Calculo da Tensao de Cisalhamento na viga
 	
 		double TCM = ((carga*(((Math.pow(altura, 2))*base)/2))/(MI*base));
 		txt_tlinha.setText(""+TCM);
                
                //Calcular deformação maxima
                if (tipo ==1 ){
                   double FM1 = ((carga * (Math.pow(comprimento, 3))) / (3 * ModulodeElasticidade * MI));
		 
                txt_deformacao.setText(""+FM1);
                }//fim if tipo 
                else if (tipo ==2){
                    double FM2 = ((carga * (Math.pow(comprimento, 3))) / (48 * ModulodeElasticidade * MI));
		txt_deformacao.setText(""+FM2);
                }//fim else tipo
                else {
                    JOptionPane.showMessageDialog(null,"Selecione o tipo da viga!");
                }
                
                
                
  }//fim do if da combo box AÇO
  else if (cbb_material.getSelectedItem() == "Madeira"){
      double ModulodeElasticidade = 13*(Math.pow(10, 9));
 	double MI;
        
        //Calculo do momento de inercia
        MI = (((Math.pow(altura,3))*base)/12);
 		txt_momento.setText(""+MI);
                
        //Calculo da tensão normal;
        double TNM = (carga/(base*altura));
 		 txt_tnormal.setText(""+TNM);
        //Calculo da Tensao de Cisalhamento na viga
        double TCM = ((carga*(((Math.pow(altura, 2))*base)/2))/(MI*base));
 		System.out.println(TCM);
                txt_tlinha.setText(""+TCM);
                //Calcular deformação maxima
                if (tipo ==1 ){
                   double FM1 = ((carga * (Math.pow(comprimento, 3))) / (3 * ModulodeElasticidade * MI));
		txt_deformacao.setText(""+FM1);
                }//fim if tipo 
                else if (tipo ==2){
                    double FM2 = ((carga * (Math.pow(comprimento, 3))) / (48 * ModulodeElasticidade * MI));
		txt_deformacao.setText(""+FM2);
                }//fim else tipo
                else {
                    JOptionPane.showMessageDialog(null,"Selecione o tipo da viga!");
                }
  }//fim do if da combo box MADEIRA
  else if (cbb_material.getSelectedItem() == "Alumínio"){
      double ModulodeElasticidade = 70 * (Math.pow(10, 9));
	double  MI;
        //Momento de inercia
        MI = (((Math.pow(altura, 3)) * base) / 12);
		
                txt_momento.setText(""+MI);
                //Calculo da tensão normal;
        double TNM = (carga/(base*altura));
 		
                txt_tnormal.setText(""+TNM);
                //Metodo para calcular a Tensao de Cisalhamento na viga
                double TCM = ((carga * (((Math.pow(altura, 2)) * base) / 2)) / (MI * base));
		txt_tlinha.setText(""+TCM);
                //Calcular deformação maxima
                if (tipo ==1 ){
                   double FM1 = ((carga * (Math.pow(comprimento, 3))) / (3 * ModulodeElasticidade * MI));
		txt_deformacao.setText(""+FM1);
                }//fim if tipo 
                else if (tipo ==2){
                    double FM2 = ((carga * (Math.pow(comprimento, 3))) / (48 * ModulodeElasticidade * MI));
		txt_deformacao.setText(""+FM2);
                }//fim else tipo
                else {
                    JOptionPane.showMessageDialog(null,"Selecione o tipo da viga!");
                }
  }//fim aluminio
  
  //fim para o btn calcular aqui embaixo
    }//GEN-LAST:event_btn_calcularActionPerformed

    private void txt_alturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alturaActionPerformed

    private void btn_limpardadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpardadosActionPerformed


        txt_altura.setText("");
        txt_base.setText("");
        txt_carga.setText("");
        txt_comprimento.setText("");
        txt_deformacao.setText("");
        txt_momento.setText("");
        txt_tlinha.setText("");
        txt_tnormal.setText("");
        altura = 0;
        base = 0;
        comprimento =0;
        carga =0;
        buttonGroup1.clearSelection();
        tipo = 0;
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_limpardadosActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed

    System.exit(0);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void cbb_materialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_materialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbb_materialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calcular;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_limpardados;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbb_material;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JRadioButton rbt_biapoiado;
    private javax.swing.JRadioButton rbt_engastado;
    private javax.swing.JTextField txt_altura;
    private javax.swing.JTextField txt_base;
    private javax.swing.JTextField txt_carga;
    private javax.swing.JTextField txt_comprimento;
    private javax.swing.JTextField txt_deformacao;
    private javax.swing.JTextField txt_momento;
    private javax.swing.JTextField txt_tlinha;
    private javax.swing.JTextField txt_tnormal;
    // End of variables declaration//GEN-END:variables
}
